// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattyhall/cb-advance-go-materials/mocking/03/client (interfaces: Client)

// Package mock_client is a generated GoMock package.
package mock_client

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "github.com/mattyhall/cb-advance-go-materials/mocking/03/client"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetUniversities mocks base method.
func (m *MockClient) GetUniversities() ([]client.University, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUniversities")
	ret0, _ := ret[0].([]client.University)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUniversities indicates an expected call of GetUniversities.
func (mr *MockClientMockRecorder) GetUniversities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUniversities", reflect.TypeOf((*MockClient)(nil).GetUniversities))
}
